"use client";

import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { QueryClient, QueryClientProvider } from "react-query";
import { poppins, playfair_display } from "./fonts";

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <body className={`${poppins.className} ${playfair_display.variable}`}>
          <div className="m-auto max-w-[90vw] xl:max-w-7xl">{children}</div>
        </body>
      </QueryClientProvider>
    </html>
  );
}
